language: python


install:
  - pip install tox-travis coveralls

script: 
  - python test/test_operations.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

services:
  - xvfb
  
after_success:
  - coveralls